from sklearn.preprocessing import MinMaxScaler, StandardScaler, LabelEncoder,OneHotEncoder
import pandas as pd
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)
data={"mark":[86,68,87,87,97,67],"avg":[0.1,0.3,0.2,0.7,0.8,0.9]}
df=pd.DataFrame(data)
print(df)
mm_scl=MinMaxScaler()
std_scl=StandardScaler()
lab_en=LabelEncoder()
df_mm=pd.DataFrame(mm_scl.fit_transform(df),columns=["mm_mark","mm_avg"])
df_std=pd.DataFrame(std_scl.fit_transform(df),columns=["std_mark","std_avg"])
final=pd.concat([df,df_mm,df_std],axis=1)
print(final)
final["age"]=lab_en.fit_transform(df["mark"])
print(final)
new_df=pd.get_dummies(final["mark"],prefix="NO.")
print(new_df)
final_1=pd.concat([final,new_df],axis=1)
print(final_1)
ohe=OneHotEncoder()
encoded_df=(ohe.fit_transform(df[["mark"]]),)
print(encoded_df)
new1=pd.DataFrame(encoded_df)
print(new1)
